#
services:
  
  # Markdown server: no stdio server available.
  markitdown:
    # <<: *workspace
    profiles: ['mcp', 'site', 'all']
    build:
      context: ..
      dockerfile_inline: |
        FROM mcp.local:base
        RUN pip3 install --break-system-packages markitdown==0.1.3 markitdown-mcp==0.0.1a4
    entrypoint: >-
      bash -x -c "markitdown-mcp --http --host 0.0.0.0 --port 80"
    # ports: ["9032:80"]
